inherit_gem:
  syntax_tree: config/rubocop.yml

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 4.0

Metrics:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always
