name: CI

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '4.0.6'

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specs
        run: bin/rspec
      - name: Run RuboCop
        run: bin/rubocop
      - name: Check Syntax Tree formatting
        run: bin/stree check Gemfile Rakefile djk_monads.gemspec "lib/**/*.rb" "spec/**/*.rb"
